sts = input('Digite algo?:')
print ('O tepo primitivo desse velor e?:',type(sts))
print ('So tem espassos?:',sts.isspace())
print ('Só tem numeros?:',sts.isnumeric())
print ('Só tem letras minusculas?:',sts.islower())
print ('É alfanumerico?:',sts.isalnum())
print ('Só tem letras maiusculas:?',sts.isalpha())
print ('Só esta em maisculas:?',sts.isupper())
print ('Está captalizada:?',sts.istitle())