sts = int(input('Digite um numero:'))
ste = (sts * 1)
std = (sts * 2)
stt = (sts * 3)
stu = (sts * 4)
sto = (sts * 5)
sty = (sts * 6)
stp = (sts * 7)
stc = (sts * 8)
stg = (sts * 9)
stv = (sts * 10)
print ('Tabuada do numero escolido é: [ {} ]  \n [ {} ] \n [ {} ] \n [ {} ] \n [ {} ] \n [ {} ] \n [ {} ]  \n [ {} ]  \n [ {} ] \n [ {} ]'.format(ste,std,stt,stu,sto,sty,stp,stc,stg,stv))