primeiro = int(input('primeiro valor'))
segundo = int(input('segundo valor'))
terceiro = int(input('teceiro valor'))
maximo = max(primeiro,segundo,terceiro)
minimo = min(primeiro,segundo,terceiro)
print('o maior valor digitado foi {}'.format(maximo))
print('o menor numero digitado foi {}'.format(minimo))
